library identifier: 'jenkinsdemo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/SpdRcr911/JenkinsDemo-Library.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
    }
}
